version: "3.9"

# See: https://github.com/microsoft/vscode-dev-containers/blob/7e2efef09632a55aaa0698ed5862336a5cd341e7/container-templates/docker-compose/.devcontainer/docker-compose.yml

services:
  editor:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.editor

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
