version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - example.env 
    environment:
      - FLASK_ENV=development 
    ports: 
      - "5000:5000"
    volumes:
      - .:/myportfolio 
    depends_on:
      - mysql

  mysql:
    container_name: mysql 
    image: mariadb 
    env_file:
      - example.env 
    volumes: 
      - mydatabase:/var/lib/mysql 

volumes: 
  mydatabase:
