name: Webhook Test

on:
  push:
    branches:
      - better-webhooks

jobs:
  deploy:
    name: 'Webhook'
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        env:
          TITLE: '🚀 Deployment Successful!'
          DESCRIPTION: '${{ github.event.head_commit.message }}'
          IMG: '{ "url": "https://cataas.com/cat" }'
          # formatted based on https://birdie0.github.io/discord-webhooks-guide/structure/embed/timestamp.html
          # milliseconds are set to 0
          TIMESTAMP: date +'%Y-%m-%dT%H:%M:%S.000Z'
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{ "embeds": [{ "title": "${{ env.TITLE }}", "description": "${{ env.DESCRIPTION }}", "image": "${{ env.IMG }}" }]}' \
            "${{ secrets.DISCORD_WEBHOOK }}"
