name: Webhook Test

on:
  push:
    branches:
      - better-webhooks

jobs:
  deploy:
    name: 'Webhook'
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{ "embeds": [{ "title": "Hello!", "description": "Hi! :grinning:" }]}' \
            "${{ secrets.DISCORD_WEBHOOK }}"
