name: Webhook Test

on:
  push:
    branches:
      - better-webhooks

jobs:
  deploy:
    name: 'Webhook'
    runs-on: ubuntu-latest
    steps:
      # https://stackoverflow.com/a/64649397
      - name: Dynamically set $DATE
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S.000Z')" >> $GITHUB_ENV

      - name: Send webhook
        env:
          TITLE: '🚀 Deployment Successful!'
          DESCRIPTION: '${{ github.event.head_commit.message }}'
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d "{ \"embeds\": [{ \"title\": \"$TITLE\", \"description\": \"$DESCRIPTION\", \"timestamp\": \"$DATE\" }]}" \
            "${{ secrets.DISCORD_WEBHOOK }}"
